spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:main;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;DEFAULT_NULL_ORDERING=HIGH
    username: sa
    password:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none
  sql:
    init:
      mode: always
      schema-locations: classpath:schema-main.sql

client:
  url: stats-server

stats:
  service:
    id: stats-server
  retry:
    max-attempts: 3
    backoff-ms: 3000

server:
  port: 0