CREATE TABLE IF NOT EXISTS categories (
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS compilations (
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(50) NOT NULL,
    pinned BOOLEAN DEFAULT FALSE
);

CREATE TABLE IF NOT EXISTS users (
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(254) NOT NULL UNIQUE,
    name VARCHAR(250) NOT NULL
);

CREATE TABLE IF NOT EXISTS locations (
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lat  FLOAT NOT NULL,
    lon  FLOAT NOT NULL,
    UNIQUE (lat, lon)
);

CREATE TABLE IF NOT EXISTS events (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_id        BIGINT NOT NULL,
    initiator_id       BIGINT NOT NULL,
    description        VARCHAR(7000) NOT NULL,
    annotation         VARCHAR(2000) NOT NULL,
    event_date         TIMESTAMP NOT NULL,
    location_id        BIGINT NOT NULL,
    paid               BOOLEAN DEFAULT FALSE,
    confirmed_requests  INTEGER DEFAULT 0,
    participant_limit  INTEGER DEFAULT 0,
    request_moderation BOOLEAN DEFAULT TRUE,
    title              VARCHAR(120) NOT NULL,
    state              VARCHAR(30) DEFAULT 'PENDING',
    published_on       TIMESTAMP,
    created_on         TIMESTAMP NOT NULL,
    CONSTRAINT fk_events_category_id FOREIGN KEY (category_id) REFERENCES categories(id),
    CONSTRAINT fk_events_location_id FOREIGN KEY (location_id) REFERENCES locations(id) ON DELETE CASCADE,
    CONSTRAINT fk_events_initiator_id FOREIGN KEY (initiator_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT chk_cnfrmd_request_limit CHECK (confirmed_requests <= participant_limit)
);

CREATE TABLE IF NOT EXISTS participation_requests (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    requester_id BIGINT NOT NULL,
    event_id     BIGINT NOT NULL,
    status       VARCHAR(30) NOT NULL,
    created_on      TIMESTAMP NOT NULL,
    CONSTRAINT fk_requests_event_id FOREIGN KEY (event_id) REFERENCES events(id) ON DELETE CASCADE,
    CONSTRAINT fk_requests_requester_id FOREIGN KEY (requester_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS events_compilations (
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id BIGINT NOT NULL,
    comp_id  BIGINT NOT NULL,
    CONSTRAINT fk_events_compilations_event_id FOREIGN KEY (event_id) REFERENCES events(id) ON DELETE CASCADE,
    CONSTRAINT fk_events_compilations_comp_id FOREIGN KEY (comp_id) REFERENCES compilations(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS comments (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    text          VARCHAR(500) NOT NULL,
    comment_id    BIGINT,
    event_id      BIGINT NOT NULL,
    author_id     BIGINT NOT NULL,
    creation_date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT fk_comments_event FOREIGN KEY (event_id) REFERENCES events(id) ON DELETE CASCADE,
    CONSTRAINT fk_comments_author FOREIGN KEY (author_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT fk_comments_parent FOREIGN KEY (comment_id) REFERENCES comments(id) ON DELETE CASCADE,
    CONSTRAINT chk_comments_ids CHECK (id != comment_id)
);

CREATE INDEX idx_comments_event_author_date
    ON comments(event_id, author_id, creation_date ASC);

CREATE INDEX idx_comments_comment_id
    ON comments(comment_id);