CREATE TABLE IF NOT EXISTS applications (
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS statistics (
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    app_id    BIGINT NOT NULL,
    uri       VARCHAR(100) NOT NULL,
    ip        VARCHAR(16) NOT NULL,
    timestamp TIMESTAMP NOT NULL,
    CONSTRAINT fk_statistics_app_id FOREIGN KEY (app_id) REFERENCES applications(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_statistics_app_id ON statistics(app_id);
CREATE INDEX IF NOT EXISTS idx_statistics_timestamp ON statistics(timestamp);
CREATE INDEX IF NOT EXISTS idx_statistics_uri ON statistics(uri);
CREATE INDEX IF NOT EXISTS idx_statistics_ip ON statistics(ip);
CREATE INDEX IF NOT EXISTS idx_statistics_uri_timestamp ON statistics(uri, timestamp);